---

- name: create sachet system group
  group:
    name: sachet
    system: true
    state: present

- name: create sachet system user
  user:
    name: sachet
    system: true
    shell: "/sbin/nologin"
    group: sachet
    createhome: false

- name: create sachet directories
  file:
    path: "{{ item }}"
    state: directory
    owner: sachet
    group: sachet
    mode: 0755
  with_items:
    - "{{ sachet_config_dir }}"

- name: install sachet from sources
  block:
    - name: install dependencies
      package:
        name: "{{ sachet_dependencies }}"
        state: present
    
    - name: go get sachet
      command: "go get -u {{ sachet_repository }}/cmd/sachet@{{ sachet_version }}"
      environment:
        GO111MODULE: "on"
        GOPATH: "{{ ansible_env.HOME }}/go"
    
    - name: propagate sachet binaries
      copy:
        remote_src: yes
        src: "{{ ansible_env.HOME }}/go/bin/sachet"
        dest: /usr/local/bin/sachet
        mode: '0755'
      notify: restart sachet
  when: ansible_facts['architecture'] != "x86_64"

- name: install sachet from github releases
  block:
    - name: download sachet binaries to local folder
      get_url:
        url: "https://{{ sachet_repository }}/releases/download/{{ sachet_version }}/sachet-{{ sachet_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp/sachet-{{ sachet_version }}.linux-{{ go_arch }}.tar.gz"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: unpack sachet binaries
      unarchive:
        src: "/tmp/sachet-{{ sachet_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/sachet-{{ sachet_version }}.linux-{{ go_arch }}"
      delegate_to: localhost
      check_mode: false

    - name: propagate sachet binaries root
      copy:
        src: "/tmp/sachet-{{ sachet_version }}.linux-{{ go_arch }}/{{ item }}"
        dest: "/usr/local/bin/{{ item }}"
        mode: 0755
        owner: root
        group: root
      with_items:
        - sachet
      notify:
        - restart sachet 
  when: ansible_facts['architecture'] == "x86_64"
