---
- name: create systemd service unit
  template:
    src: prometheus-msteams.service.j2
    dest: /etc/systemd/system/prometheus-msteams.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus-msteams

- name: copy custom template files
  copy:
    src: "{{ item }}"
    dest: "{{ prometheus_msteams_config_dir }}/"
    owner: root
    group: "{{ _prometheus_msteams_system_group }}"
    mode: 0640
  with_fileglob:
    - ../files/*.tmpl
  notify: restart prometheus-msteams

- name: Create prometheus-msteams main configuration file
  template:
    src: config.yml.j2
    dest: "{{ prometheus_msteams_config_dir }}/config.yml"
    owner: root
    group: "{{ _prometheus_msteams_system_group }}"
    mode: 0640
  notify: restart prometheus-msteams

- name: Enable and start prometheus-msteams systemd unit
  systemd:
    name: prometheus-msteams
    enabled: true
    state: started
    daemon_reload: true
