prometheus_static_targets_files: "{{playbook_dir}}/custom/oci/*targets*.yml"
prometheus_alert_rules_files: "{{playbook_dir}}/custom/oci/*alerts.rules"
prometheus_db_dir: /data/prometheus

prometheus_alertmanager_config:
- scheme: http
  static_configs:
  - targets: ["127.0.0.1:9093"]

alertmanager_smtp:
  from: 'alertas@ndd.tech'
  smarthost: 'mail.nfendd.com.br:25'
  auth_username: 'alertas.ngeria'
  auth_password: 'TipUPreqebr0'
  require_tls: false

alertmanager_receivers:

- name: 'sre-team-telegram'
  webhook_configs:
  - url: 'http://localhost:9876/alert'
    max_alerts: 5      

- name: 'sre-team-msteams'
  webhook_configs:
  - url: 'http://localhost:2000/sre_msteams'

- name: alertsnitch
  webhook_configs:
    - url: http://br-oci-nigl01.dcndd.local:9567/webhook

- name: keepaneye
  webhook_configs:
    - url: https://webhook.site/13a22528-765a-4ad7-8a15-d3f516a69fe9    

- name: 'sre-team-mail'
  email_configs:
  - to: 'maick.souza@ndd.tech' 
    headers:
      subject: '{{ "{{" }} template "email.ndd.subject" . {{ "}}" }}' 
    html: '{{ "{{" }} template "ndd-email" . {{ "}}" }}' 

# ALERTMANAGER ROUTES

alertmanager_route:
  repeat_interval: 12h
  receiver: sre-team-msteams
  group_by: [alertname, ambiente]
  routes:
  
  - match:
      sre1_team: "yes"
    receiver: "sre-team-msteams"
    continue: false
    routes:
    - receiver: "sre-team-telegram"
      continue: true
      mute_time_intervals:
      - semana_comercial       
    - receiver: "sre-team-mail"
      continue: true
      repeat_interval: 24h
      mute_time_intervals:
      - semana_comercial      
    - receiver: "sre-team-msteams"
      continue: true

  - match:
      sre_team: "yes"
    receiver: "alertsnitch"
    continue: true
    routes:
    - receiver: "alertsnitch"
      continue: true
    - receiver: 'sre-team-mail'
      continue: true               
    - receiver: "keepaneye"
      continue: true   

### FIM ALERMANAGER ROUTES 


### GERENCIAMENTO DE MUTE INTERVALS

alertmanager_mute_time_intervals:
- name: semana_comercial
  time_intervals:
  # alertas ativos das 8:00 as 18:00 - horario deve ser preenchido utc
  - times:
    - start_time: "00:00"
      end_time: "11:00"
    - start_time: "21:00"
      end_time: "24:00"
    weekdays: ['monday:friday']
  - weekdays: ['saturday' , 'sunday'] 

- name: semana_plantao
  time_intervals:
  # Mute das 8:00 as 12:00 e das 13:00 as 18:00 de segunda a sexta - horario deve ser preenchido utc
  - times:
    - start_time: "11:00"
      end_time: "15:00"
    - start_time: "16:00"
      end_time: "21:00"
    weekdays: ['monday:friday']
    #weekdays: ['monday', 'tuesday', 'thursday', 'friday']

### FIM  GERENCIAMENTO DE MUTE INTERVALS


prometheus_msteams_connectors:
- sre_msteams: "https://nddsa.webhook.office.com/webhookb2/a61202bc-6538-4e6e-b458-9596cc57224e@717144d2-6d9f-42a1-b56d-42afc3753ec3/IncomingWebhook/2d1f9c7897934f829caaefd216d3d806/86d9840c-7329-4beb-b4e9-8f6221d3a85f"
- support_msteams: "https://nddsa.webhook.office.com/webhookb2/4bcb6680-a56a-4fbb-a5c6-1c7c3b0d6978@717144d2-6d9f-42a1-b56d-42afc3753ec3/IncomingWebhook/deb28d346f8f4c47ab965812578c7993/c95c7c84-d261-4c29-bf9a-d8dcd8c584e9"

sachet_templates:
- "{{ sachet_config_dir }}/telegram.tmpl"
- "{{ sachet_config_dir }}/telegram-short.tmpl"

sachet_providers:
  telegram:
    token: "1226791700:AAEkQSR2CfnQI16NcqKQxoC_UpZ-k0Se18A"

sachet_receivers:
- name: 'sre-team-telegram'
  provider: 'telegram'
  to: # the chat id of a user. Get yours at https://telegram.me/userinfobot
  #- '1169058584' # William
  - '1258790902' # Vinicius Matos
  text: '{{ "{{" }}  template "telegram_message" . {{ "}}" }}'

# FRETE TELEGRAM

- name: 'frete-team-telegram'
  provider: 'telegram'
  to: # the chat id of a user. Get yours at https://telegram.me/userinfobot
  # - '1202803478' # Douglas
  - '5779892612' # Gabriel Pires
  - '6000887212' # Plantão Frete
  text: '{{ "{{" }}  template "telegram_message" . {{ "}}" }}'

# CARGO

- name: 'cargo-team-telegram'
  provider: 'telegram'
  to: # the chat id of a user. Get yours at https://telegram.me/userinfobot
  # - '696601893' # Leonardo Nunes
  # - '1419105131' # Vagner de Moraes
  # - '2114592285' # Soraia da luz
  - '1218218124' # Fernando Ben Hur 
  # - '1258790902' # Vinicius Matos  
  text: '{{ "{{" }}  template "telegram_message" . {{ "}}" }}'

- name: 'move-team-telegram'
  provider: 'telegram'
  to: # the chat id of a user. Get yours at https://telegram.me/userinfobot
  - '1218218124' # Fernando Ben Hur 
  - '5779892612' # Gabriel Pires
  - '1258790902' # Vinicius Matos  
  text: '{{ "{{" }}  template "telegram_message" . {{ "}}" }}'


# NFCE TELEGRAM

- name: 'nfce-team-telegram'
  provider: 'telegram'
  to: # the chat id of a user. Get yours at https://telegram.me/userinfobot
  - '1311238041' # Victor
  - '5595444700' # Leticia
  text: '{{ "{{" }}  template "telegram_message" . {{ "}}" }}'

# PRINT TELEGRAM

- name: 'print-team-telegram'
  provider: 'telegram'
  to: # the chat id of a user. Get yours at https://telegram.me/userinfobot
  - '6036279756' # Moises Bittencourt
  text: '{{ "{{" }}  template "telegram_message" . {{ "}}" }}'  


# FIM TIMES DE TLEGRAM

# JOBS FD

prometheus_scrape_configs:

### Job Federation une as bases oci x cotia, deve-se incluir o produto conforme abaixo

- job_name: 'federate-skyview'
  scrape_interval: 20s
  scrape_timeout: 19s
  honor_labels: true
  metrics_path: '/federate'
  params:
    'match[]':
      - '{produto="skyview"}'
      - '{__name__=~"job:.*"}'
  static_configs:
    - targets:
      - '138.94.211.13:9100'
      labels:
        produto: skyview
        ambiente: skyview-cotia
        env: prd
        job: federate

- job_name: 'federate-dcnfse'
  scrape_interval: 20s
  scrape_timeout: 19s
  honor_labels: true
  metrics_path: '/federate'
  params:
    'match[]':
      - '{produto="dcnfse"}'
      - '{__name__=~"job:.*"}'
  static_configs:
    - targets:
      - '138.94.211.13:9100'
      labels:
        produto: skyview
        ambiente: skyview-cotia
        env: prd
        job: federate

- job_name: 'federate-orbix-am'
  scrape_interval: 20s
  scrape_timeout: 19s
  honor_labels: true
  metrics_path: '/federate'
  params:
    'match[]':
      - '{produto="orbix",ambiente="orbix-am"}'
      - '{__name__=~"job:.*"}'
  static_configs:
    - targets:
      - '20.22.58.252:9090'
      labels:
        produto: orbix
        ambiente: orbix-am
        env: prd
        job: federate        

- job_name: 'federate-orbix-eu'
  scrape_interval: 20s
  scrape_timeout: 19s
  honor_labels: true
  metrics_path: '/federate'
  params:
    'match[]':
      - '{produto="orbix",ambiente="orbix-eu"}'
      - '{__name__=~"job:.*"}'
  static_configs:
    - targets:
      - '20.79.140.50:9090'
      labels:
        produto: orbix
        ambiente: orbix-eu
        env: prd
        job: federate   


###

- job_name: "file-servicediscovery"
  scrape_interval: 20s
  scrape_timeout: 19s
  file_sd_configs:
  - files:
    - "{{ prometheus_config_dir }}/file_sd/*-targets.yml"
    refresh_interval: 10m

- job_name: "file-servicediscovery-1m"
  scrape_interval: 1m
  scrape_timeout: 59s
  file_sd_configs:
  - files:
    - "{{ prometheus_config_dir }}/file_sd/*-targets-1m.yml"
    refresh_interval: 10m

- job_name: "file-servicediscovery-3m"
  scrape_interval: 3m
  scrape_timeout: 2m
  file_sd_configs:
  - files:
    - "{{ prometheus_config_dir }}/file_sd/*-targets-3m.yml"
    refresh_interval: 10m

- job_name: "file-servicediscovery-5m"
  scrape_interval: 5m
  scrape_timeout: 2m
  file_sd_configs:
  - files:
    - "{{ prometheus_config_dir }}/file_sd/*-targets-5m.yml"
    refresh_interval: 60m
  # relabel_configs:
  #   - source_labels: []
  #     target_label: 'data'
  #     replacement: '(time - 86400) | formatTimestamp "2006-01-02"'
  # Funciona, mas não realiza o calculo


#########################################################################

  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 127.0.0.1:9115
# FIM  JOB BLACKBOX
